/**
 * Copyright 2010, 2017 Sebastian Ritter
 *
 * Lizenziert unter der EUPL, nur Version 1.1 ("Lizenz");
 * 
 * Sie dürfen dieses Werk ausschließlich gemäß
 * dieser Lizenz nutzen.
 * Eine Kopie der Lizenz finden Sie hier:
 *
 * http://ec.europa.eu/idabc/eupl5
 * 
 * Sofern nicht durch anwendbare Rechtsvorschriften
 * gefordert oder in schriftlicher Form vereinbart, wird
 * die unter der Lizenz verbreitete Software "so wie sie
 * ist", OHNE JEGLICHE GEWÄHRLEISTUNG ODER BEDINGUNGEN -
 * ausdrücklich oder stillschweigend - verbreitet.
 * Die sprachspezifischen Genehmigungen und Beschränkungen
 * unter der Lizenz sind dem Lizenztext zu entnehmen.
 */
package biz.ritter.develop.cobol.core;

/**
 * @author Sͬeͥbͭaͭsͤtͬian
 *
 */
public class COBOL85LanguageImpl implements COBOLLanguage {
//TODO LanguageImpl need to export in own plugins and COBOL-74, COBOL-85, COBOL-2002 per default mit ausliefern OpenCOBOL 1.0, 1.1, 1.2 sowie TINY COBOL 0.64 mit ausliefern
  static COBOL85LanguageImpl instance;
  
  public COBOL85LanguageImpl () {}
  
  public static COBOL85LanguageImpl createCOBOL85LanguageImpl() {
    if (null == instance) {
      instance = new COBOL85LanguageImpl();
    }
    return instance;
  }
  
  /* (non-Javadoc)
   * @see biz.ritter.develop.cobol.core.COBOLLanguage#getFigurativeConstants()
   */
  @Override
  public String[] getFigurativeConstants() {
    return FIGURATIVE_CONSTANTS;
  }
  
  /* (non-Javadoc)
   * @see biz.ritter.develop.cobol.core.COBOLLanguage#getSpecialRegisters()
   */
  @Override
  public String[] getSpecialRegisters() {
    return SPECIAL_REGISTERS;
  }
  
  /* (non-Javadoc)
   * @see biz.ritter.develop.cobol.core.COBOLLanguage#getKeywords()
   */
  @Override
  public String[] getKeywords() {
    return KEYWORDS;
  }
  
  /* (non-Javadoc)
   * @see biz.ritter.develop.cobol.core.COBOLLanguage#getDeprecatedKeywords()
   */
  @Override
  public String[] getDeprecatedKeywords() {
    return DEPRECATED_KEYWORDS;
  }

  @Override
  public COBOLDialectDescriptor getDialectInformations() {
    return new COBOLDialectDescriptor() {

      @Override
      public String getName() {
        return "ISO COBOL 85";
      }

      @Override
      public String getVersion() {
        return "COBOL 85";
      }
    };
  }
  
  /**
   * Figurative constants of COBOL programming language
   */
  private static final  String[] FIGURATIVE_CONSTANTS= {
      "ALL","LOW-VALUE","LOW-VALUES","HIGH-VALUE","HIGH-VALUES","SPACE",
      "SPACES","QUOTE","QUOTES","ZERO","ZEROS","ZEROES"
  };

  /**
   * Special registers
   */
  private static final  String[] SPECIAL_REGISTERS= {
      "RETURN-CODE","LINE-COUNTER","PAGE-COUNTER"
  };

  private static final String [] DEPRECATED_KEYWORDS = {
    "ALTER", "AUTHOR","DATE-COMPILED","DATE-WRITTEN","GOTO"
  };
  
  /**
   * Stores reserved words
   */
  protected static final String[] KEYWORDS= {
    "ACCEPT",
    "ACCESS",
    "ACTUAL",
    "ADD",
    "ADDRESS",
    "ADVANCING",
    "AFTER",
    "ALPHABET",
    "ALPHABETIC",
    "ALPHABETIC-LOWER",
    "ALPHABETIC-UPPER",
    "ALPHANUMERIC",
    "ALPHANUMERIC-EDITED",
    "ALSO",
    "ALTERNATE",
    "AND",
    "ANY",
    "APPLY",
    "ARE",
    "AREA",
    "AREAS",
    "ARITHMETIC",
    "AS",
    "ASCENDING",
    "ASSIGN",
    "AT",
    "AUTO",
    "BASED",
    "BACKGROUND-COLOR",
    "BASED-STORAGE",
    "BEFORE",
    "BEGINNING",
    "BELL",
    "BINARY",
    "BIT",
    "BITS",
    "BLANK",
    "BLINK",
    "BLOCK",
    "BOOLEAN",
    "BOTTOM",
    "BY",
    "CALL",
    "CANCEL",
    "CBL",
    "CD",
    "CF",
    "CH",
    "CHANGED",
    "CHARACTER",
    "CHARACTERS",
    "CLOCK-UNITS",
    "CLOSE",
    "COBOL",
    "COLLATING",
    "COLUMN",
    "COMMA",
    "COMMAND",
    "COMMON",
    "COM-REG",
    "COMP",
    "COMP-1",
    "COMP-2",
    "COMP-3",
    "COMP-4",
    "COMP-5",
    "COMPLEX",
    "COMPUTATIONAL",
    "COMPUTATIONAL-1",
    "COMPUTATIONAL-2",
    "COMPUTATIONAL-3",
    "COMPUTATIONAL-4",
    "COMPUTATIONAL-5",
    "COMPUTE",
    "CONFIGURATION",
    "CONSTANT",
    "CONTAINED",
    "CONTAINS",
    "CONTENT",
    "CONTINUE",
    "CONTROL",
    "CONTROL-CHARACTER",
    "CONTROLS",
    "CONVERTING",
    "COPY",
    "CORE-INDEX",
    "CORR",
    "CORRESPONDING",
    "COUNT",
    "CRP",
    "CRT",
    "CRT-UNDER",
    "CURRENCY",
    "CURRENT",
    "CURSOR",
    "DATA",
    "DATE",
    "DAY",
    "DAY-OF-WEEK",
    "DB",
    "DB-ACCESS-CONTROL-KEY",
    "DB-DATA-NAME",
    "DB-EXCEPTION",
    "DB-RECORD-NAME",
    "DB-SET-NAME",
    "DB-STATUS",
    "DECIMAL-POINT",
    "DECLARATIVES",
    "DEFAULT",
    "DELETE",
    "DELIMITED",
    "DELIMITER",
    "DEPENDING",
    "DESCENDING",
    "DETAIL",
    "DEVICE",
    "DIRECT",
    "DISABLE",
    "DISJOINING",
    "DISPLAY",
    "DISPLAY-1",
    "DISPLAY-EXIT",
    "DIVIDE",
    "DIVISION",
    "DOWN",
    "DUPLICATE",
    "DUPLICATES",
    "DYNAMIC",
    "ELSE",
    "EMPTY",
    "ENABLE",
    "END",
    "END-ACCEPT",
    "END-ADD",
    "END-CALL",
    "END-COMPUTE",
    "END-DELETE",
    "END-DISPLAY",
    "END-DIVIDE",
    "END-EVALUATE",
    "END-EXEC",
    "END-IF",
    "END-INVOKE",
    "END-MULTIPLY",
    "END-OF-PAGE",
    "END-PERFORM",
    "END-READ",
    "END-RECEIVE",
    "END-RETURN",
    "END-REWRITE",
    "END-SEARCH",
    "END-START",
    "END-STRING",
    "END-SUBTRACT",
    "END-UNSTRING",
    "END-WRITE",
    "ENDING",
    "ENTER",
    "ENTRY",
    "ENVIRONMENT",
    "EOL",
    "EQUAL",
    "EQUALS",
    "ERASE",
    "ERROR",
    "EVALUATE",
    "EVERY",
    "EXAMINE",
    "EXCEEDS",
    "EXCEPTION",
    "EXCEPTION-OBJECT",
    "EXCLUSIVE",
    "EXEC",
    "EXIT",
    "EXTEND",
    "EXTERNAL",
    "FD",
    "FETCH",
    "FILE",
    "FILE-CONTROL",
    "FILE-LIMIT",
    "FILE-LIMITS",
    "FILES",
    "FILLER",
    "FINAL",
    "FIND",
    "FIRST",
    "FOOTING",
    "FOR",
    "FOREGROUND-COLOR",
    "FORMAT",
    "FORMATTED",
    "FREE",
    "FROM",
    "FULL",
    "FUNCTION",
    "GENERATE",
    "GET",
    "GIVING",
    "GLOBAL",
    "GO",
    "GOBACK",
    "GREATER",
    "GRID",
    "GROUP",
    "HEADING",
    "HIGHLIGHT",
    "I-O",
    "I-O-CONTROL",
    "ID",
    "IDENTIFICATION",
    "IF",
    "IN",
    "INCLUDE",
    "INDEX",
    "INDEXED",
    "INDICATE",
    "INHERITS",
    "INITIAL",
    "INITIALIZE",
    "INITIATE",
    "INPUT",
    "INPUT-OUTPUT",
    "INSPECT",
    "INSTALLATION",
    "INTO",
    "INVALID",
    "INVARIANT",
    "INVOKE",
    "IS",
    "JAPANESE",
    "JOB",
    "JOINING",
    "JUST",
    "JUSTIFIED",
    "KANJI",
    "KEEP",
    "KEY",
    "LABEL",
    "LAST",
    "LD",
    "LEADING",
    "LEFT",
    "LEFTLINE",
    "LEFT-JUSTIFY",
    "LENGTH",
    "LESS",
    "LIMIT",
    "LIMITED",
    "LIMITS",
    "LINAGE",
    "LINE",
    "LINES",
    "LINKAGE",
    "LOCK",
    "LOWLIGHT",
    "MEMBER",
    "MEMORY",
    "MERGE",
    "MESSAGE",
    "MODIFY",
    "MODULES",
    "MORE-LABELS",
    "MOVE",
    "MULTICON",
    "MULTICONVERSATION-MODE",
    "MULTIPLE",
    "MULTIPLY",
    "NAMED",
    "NATIVE",
    "NEGATIVE",
    "NEXT",
    "NOMINAL",
    "NONE",
    "NOT",
    "NUMBER",
    "NUMERIC",
    "NUMERIC-EDITED",
    "OBJECT-COMPUTER",
    "OCCURS",
    "OFF",
    "OMITTED",
    "ON",
    "ONLY",
    "OPEN",
    "OPTIONAL",
    "OR",
    "ORDER",
    "ORGANIZATION",
    "OTHER",
    "OTHERWISE",
    "OUTPUT",
    "OVERFLOW",
    "OVERLINE",
    "OVERRIDE",
    "OWNER",
    "PACKED-DECIMAL",
    "PADDING",
    "PAGE",
    "PASSWORD",
    "PERFORM",
    "PIC",
    "PICTURE",
    "PLUS",
    "POINTER",
    "POSITION",
    "POSITIONING",
    "POSITIVE",
    "PREFIX",
    "PRESENT",
    "PREVIOUS",
    "PRINTING",
    "PRIOR",
    "PROCEDURE",
    "PROCEDURES",
    "PROCEED",
    "PROCESSING",
    "PROGRAM",
    "PROGRAM-ID",
    "PROMPT",
    "PROPERTY",
    "PROTECTED",
    "PROTOPTYPE",
    "PURGE",
    "QUEUE",
    "RAISE",
    "RAISING",
    "RANDOM",
    "RANGE",
    "RD",
    "READ",
    "READY",
    "REALM",
    "RECEIVE",
    "RECONNECT",
    "RECORD",
    "RECORD-NAME",
    "RECORD-OVERFLOW",
    "RECORDING",
    "RECORDS",
    "REDEFINES",
    "REEL",
    "REFERENCE",
    "REFERENCES",
    "RELATION",
    "RELATIVE",
    "RELEASE",
    "RELOAD",
    "REMAINDER",
    "REMARKS",
    "REMOVAL",
    "RENAMES",
    "REPEATED",
    "REPLACE",
    "REPLACING",
    "REPORT",
    "REPORTING",
    "REPORTS",
    "REPOSITORY",
    "RERUN",
    "REQUIRED",
    "RESERVE",
    "RESET",
    "RETAINING",
    "RETRIEVAL",
    "RETURN",
    "RETURNING",
    "REVERSED",
    "REWIND",
    "REWRITE",
    "RIGHT",
    "RIGHT-JUSTIFY",
    "ROUNDED",
    "SAME",
    "SCREEN",
    "SD",
    "SEARCH",
    "SECTION",
    "SECURITY",
    "SECURE",
    "SEEK",
    "SEGMENT",
    "SEGMENT-LIMIT",
    "SELECT",
    "SELECTED",
    "SELECTIVE",
    "SEND",
    "SENTENCE",
    "SEPARATE",
    "SEQUENCE",
    "SEQUENTIAL",
    "SERVICE",
    "SESSION",
    "SET",
    "SHARED",
    "SHIFT-IN",
    "SHIFT-OUT",
    "SIGN",
    "SIMPLE",
    "SINGLE",
    "SIZE",
    "SORT",
    "SORT-CONTROL",
    "SORT-CORE-SIZE",
    "SORT-FILE-SIZE",
    "SORT-MESSAGE",
    "SORT-MERGE",
    "SORT-MODE-SIZE",
    "SORT-RETURN",
    "SOURCE",
    "SOURCE-COMPUTER",
    "SPACE-FILL",
    "SPECIAL-NAMES",
    "STANDARD",
    "START",
    "STATION",
    "STATIONS",
    "STATUS",
    "STOP",
    "STORE",
    "STRING",
    "SUBRANGE",
    "SUBTRACT",
    "SUCCESSIVE",
    "SUFFIX",
    "SUM",
    "SUPER",
    "SUPPRESS",
    "SYMBOLIC",
    "SYNC",
    "SYNCHRONIZED",
    "TABLE",
    "TALLY",
    "TALLYING",
    "TAPE",
    "TENANT",
    "TERMINAL",
    "TERMINATE",
    "TEST",
    "THAN",
    "THEN",
    "THROUGH",
    "THRU",
    "TIME",
    "TIMES",
    "TITLE",
    "TO",
    "TOP",
    "TRACE",
    "TRACK",
    "TRACK-AREA",
    "TRACK-LIMIT",
    "TRACK-OVERFLOW",
    "TRACKS",
    "TRAILING",
    "TRAILING-SIGN",
    "TRANSACTION",
    "TRUE",
    "TYPE",
    "TYPEDEF",
    "UNDERLINE",
    "UNIT",
    "UNIVERSAL",
    "UNLOCK",
    "UNSTRING",
    "UNTIL",
    "UP",
    "UPDATE",
    "UPON",
    "USAGE",
    "USAGE-MODE",
    "USE",
    "USING",
    "VALID",
    "VALIDATE",
    "VALUE",
    "VALUES",
    "VARYING",
    "WAIT",
    "WHEN",
    "WHEN-COMPILED",
    "WITH",
    "WITHIN",
    "WORDS",
    "WORKING-STORAGE",
    "WRITE",
    "WRITE-ONLY",
    "ZERO-FILL"
  };

  @Override
  public COBOLInstrinctFunctionDescriptor[] getInstrinctFunctionInformations() {
    return new COBOLInstrinctFunctionDescriptor [] {};
  }
}
